SciML/Static.jl

Project.toml, src/static_implementation.jl, test/runtests.jl
Highlight is that `StaticSymbol(static(:x), static(:y))` now results in `static(:xy)` and is type stable.
=> More StaticSymbol constructors

Project.toml, src/static_implementation.jl, test/runtests.jl
- `eachop` previously accepted one or two repeating arguments to be
passed to `op` for each iteration. Any number of arguments can now be
used. Same for `eachop_tuple`. They each have small doc strings but
probably shouldn't be considered public API.
- `@nif` wasn't imported with `Base.Cartesian` before
- test `permute` and a `StaticSymbol` constructor
=> Rework eachop, bug fixes, and test coverage

Project.toml, README.md, src/Static.jl, src/float.jl, src/static_implementation.jl, test/float.jl, test/runtests.jl
This adds `StaticFloat` which is a static version of `Float64`. Originally I had it follow the behavior of `Int` so that 32 bit systems used `Float32`, but I figured it made more sense to follow the pattern of `float(::Int)` where both `Int32` and `Int64` convert to `Float64`.
Copied test from Octavian.jl for this too.
@DilumAluthge , does this accomplish what you need for Octavian.jl?
~EDIT: Forgot to mention there is an ambiguity issue for 1.2 for `promote_type`. I still need to fix that...~
done
=> StaticFloat

Project.toml, src/static_implementation.jl, test/runtests.jl
Correcting a missed opportunity. Now when doing things like `&(::Bool, ::False)` we can return static values b/c it doesn't matter what the first value is.
=> Improve bitwise operators

Project.toml, src/Static.jl, src/static_implementation.jl, test/runtests.jl
We have `StaticFloat64` so `gt`/`eq`/etc are useful outside of `StaticInt`. These changes also support any additional future static types that may come around by using `is_static`. That way downstream packages can define their own static types and get all the same optimized functions working.
=> Generalize comparison methods

src/Static.jl, test/runtests.jl
The motivation, before::
```julia
julia> ArrayInterface.static_step(Int32(-10):Int32(10))
ERROR: There is no static alternative for type Int32.
Stacktrace:
[1] error(s::String)
@ Base ./error.jl:33
[2] _no_static_type(x::Any)
@ Static ~/.julia/packages/Static/I7z33/src/Static.jl:74
[3] static(x::Int32)
@ Static ~/.julia/packages/Static/I7z33/src/Static.jl:66
[4] maybe_static
@ ~/.julia/packages/Static/I7z33/src/static_implementation.jl:126 [inlined]
[5] static_step(x::UnitRange{Int32})
@ ArrayInterface ~/.julia/packages/ArrayInterface/CiK9Q/src/ArrayInterface.jl:42
[6] top-level scope
@ REPL[11]:1
```
After:
```julia
julia> ArrayInterface.static_step(Int32(-10):Int32(10))
static(1)
```
Perhaps I should just call `convert` instead of using `%`, as half of `UInt`s (for example) are …
=> Promote smaller integer types for `static`

Project.toml, src/Static.jl, src/bool.jl, src/int.jl, src/symbol.jl, test/runtests.jl
There was a little reorganization here but this ones essentially about not generating extra code when checking traits using `@nospecialize`
=> Limit needless code gen with nospecialize

Project.toml, src/Static.jl
ref https://github.com/SciML/Static.jl/pull/16#issuecomment-917209061,
https://github.com/JuliaArrays/ArrayInterface.jl/pull/204#issuecomment-917201248
cc @MasonProtter
fixes #17
=> don't hardcode version for `@constprop`

src/float.jl
This PR removes the `Base.@pure`s from `float.jl`. It also deletes an extra empty line from `float.jl`
=> remove `@pure`

Project.toml, src/float.jl, test/float.jl
This PR adds the lines
```julia
@inline function Base.exponent(::StaticFloat64{M}) where {M}
static(exponent(M))
end
for f in (:sin, :cos, :tan, :asin, :atan, :acos,
:sinh, :cosh, :tanh, :asinh, :acosh, :atanh,
:exp, :exp2, :exp10, :expm1, :log, :log2, :log10, :log1p,
:cbrt)
@eval @generated function (Base.$f)(::StaticFloat64{M}) where {M}
Expr(:call, Expr(:curly, :StaticFloat64, $f(M)))
end
end
```
and relevant tests. Closes https://github.com/SciML/Static.jl/issues/31
=> add floating point ops from Base

Project.toml, src/tuples.jl, test/runtests.jl
When I first wrote this method it used `===` to evaluate equality after testing if the collection was static or not. Consequently, mixed dynamic/static collections would miss values that were `==` but not `===`. This now works and has additional tests for that.
=> Fix `find_first_eq`

Project.toml, src/symbol.jl
previously was comparing x to x instead of x to y
=> Fixe `==` for symbols

Project.toml, src/tuples.jl
While updating LoopVectorization I found the need to account for empty tuples on `eachop`.
=> Fix recursion to zero length eachop

Project.toml, src/Static.jl, src/int.jl, src/tuples.jl, test/runtests.jl
This reverts commit 63b791b1e602b6cefe598c46bd306b861397828a.
This reverts commit f854a705fbf7ef7db4535ea1503b0c2bad6b491a.
This reverts commit ca7f1edbfc60dba22ee2f538ca22ca9826c07099.
Let's see who wins the race.
=> Revert "Return `missing` instead of `nothing`." and adjust find_first_eq

Project.toml, src/Static.jl, src/bool.jl, src/float.jl, src/int.jl, src/symbol.jl
* `string(::Symbol)` drops the `:` precursor, but we want that shown for
`static(::Symbol)`. Now all show methods go through `string` for consistency.
* Deleted Julia v1.2 specific method b/c we don't support prior to Julia
v1.6 anymore
=> Fix symbol printing

src/float.jl, src/int.jl, test/runtests.jl
Reverts to prior behavior and fixes #58. @chriselrod, It seems like we should only return `StaicInt{0}` when multiplied with other integers because we should promote. Would that break anything on your end?
=> Propagate static(0) * x

Project.toml, src/int.jl
This increases invalidations on nightly and isn't really necessary
=> Don't define `>` for `StaticInt`

Project.toml, src/Static.jl
I found that many test failures in VectorizationBase on Static v0.7 were due to `StaticInt` not being an integer when passed to `ntuple(f, ::StaticInt)`. I tested load times here and didn't see any consistent increase due to the additional method here and there were no additional invalidations.
=> `StaticInt` support for `ntuple`

Project.toml, src/Static.jl, test/runtests.jl
Supports `invperm` for tuple of `StaticInt`. This also allows `static(x)` to simply return `x` if it is a singleton type, instead of erroring.
=> static-invperm

Project.toml, src/Static.jl, test/runtests.jl
https://github.com/JuliaLinearAlgebra/Octavian.jl/pull/147
=> Define `real` and `imag` for StaticInteger

README.md
My original attempt at the README was mostly intended to illustrate how we approached creating the types here, but there's a pretty compelling argument to be made that there shouldn't be anymore types that are explicitly static (such as the current `StaticChar` example).
This new README focuses more on basic definitions and using the types defined herein.
=> More informative README (issue #23)

Project.toml, src/Static.jl, src/ranges.jl, test/ranges.jl, test/runtests.jl
I had to manually define a bit more to get this working outside of ArrayInterface (not `known_*` traits) but it's probably better to avoid the type piracy we currently are doing with `StaticInt` range constructors in downstream packaging. 
Solves #41
=> Move ranges from ArrayInterface to Static

Project.toml, src/Static.jl, test/runtests.jl
With the arrival of assumed effects in the latest versions of Julia, I've found that static types are either perfectly inferred or cannot be inferred at all. The result is often the difference between the compiler inferring "total" effects or no effects at all.
This PR passes all values lowered through `known` and `dynamic` through one of `_return_<int/symbol/float>` methods. This is done instead of a type assertion becuause it narrows down potentially dynamic calls to a clear dispatch pattern and inferred type since Julia currently doesn't enforce that the type call `T(x)` return's `T`.
=> Ensure inference never completely fails

Project.toml, src/Static.jl, test/runtests.jl
These methods were missing. After this,
```julia
julia> mod(static(2), 2)
0
```
=> Specialize mod for real arguments

src/Static.jl, test/runtests.jl
Fixes https://github.com/SciML/Static.jl/issues/108
=> fix ==, StaticBool promotion

Project.toml, src/Static.jl, test/runtests.jl
Right now all tests are failing because of the one line `Aqua.test_all(Static, piracy = false)`. I tried to look at what other SciML repos are doing to fix this but it would probably be best of @ChrisRackauckas or some other SciML expert ensures this PR goes about this correctly.
=> Fix Aqua related testing

.github/workflows/Downstream.yml, .github/workflows/ci.yml, Project.toml, src/Static.jl, test/runtests.jl
Fixes #124 .  This addresses the need to do
```julia
nt = (a=1, b=2, c=3)
nt[(static(:a), static(:b))]
```
This is a follow-up to https://github.com/SciML/Static.jl/issues/120 and https://github.com/SciML/Static.jl/pull/121.
As noted in https://github.com/SciML/Static.jl/pull/121, the Aqua tests currently fail, but the tests pass otherwise.
=> Add another missing NamedTuple getindex method for StaticSymbol

src/Static.jl, test/runtests.jl
This seems largely unused but invalidates. Might as well remove it?
=> Remove static pointer arithmetic

Project.toml, docs/make.jl, src/Static.jl, src/ranges.jl, test/ranges.jl, test/runtests.jl
This makes this package invalidation-free and precompiles based on an earlier state which matches Symbolics and thus reduces/removed repeated invalidation handling. This shouldn't effect compile at all from where we were before, but it will change precompilation time as it moves it all to a shared moment.
=> Add CommonWorldInvalidations world

src/Static.jl
This PR closes #132. 
Behavior does not change with the current Julia release, and the ambiguity is resolved for the nightly release.
Changes the argument types for the `any` and `all` methods on tuples to not rely on julia base definining
`all(::Tuple{}) = true` and `any(::Tuple{}) = false`.
[contributor guidelines](https://github.com/SciML/.github/blob/master/CONTRIBUTING.md), in particular the [SciML Style Guide](https://github.com/SciML/SciMLStyle) and
[COLPRAC](https://github.com/SciML/COLPRAC).
This is not an issue with the current Julia release, but it likely will be in the future.
=> Restrict `any` and all` argument type bounds
